Louis: tp7Louis.c sigUtils.h sigUtils.o forkUtils.h forkUtils.o
	cc -o Louis tp7Louis.c sigUtils.o forkUtils.o

Ella:
	cc -o Ella  tp7bis.c

#sigUtils.o: sigUtils.c
#	cc -c sigUtils.c
#
#forkUtils.o: forkUtils.c
#	cc -c
